/*
 *		$Archive: /video/Nba/audinfo.c $
 *		$Revision: 14 $
 *		$Date: 3/23/99 4:05p $
 *
 *		Copyright (c) 1997, 1998 Midway Games Inc.
 *		All Rights Reserved
 *
 *		This file is confidential and a trade secret of Midway Games Inc.
 *		Use, reproduction, adaptation, distribution, performance or
 *		display of this computer program or the associated audiovisual work
 *		is strictly forbidden unless approved in writing by Midway Games Inc.
 */

#ifdef INCLUDE_SSID
char *ss_audinfo_c = "$Workfile: audinfo.c $ $Revision: 14 $";
#endif

/*
 *		SYSTEM INCLUDES
 */

#include	<stdio.h>
#include	<goose/goose.h>

/*
 *		USER INCLUDES
 */

#include	"game.h"
#include	"audits.h"

void do_team_percent_aud(int);
void clear_coin_audits(void);
void clear_credits_audits(void);
void clear_game_audits(void);
void clear_team_audits(void);
void clear_feature_audits(void);
int  check_coin_audits(void);
int  check_credits_audits(void);
int  check_game_audits(void);
int  check_team_audits(void);
int check_feature_audits(void);
int  check_all_audits(void);


// Table used to clear out coin audits
static int	coin_audits[] = {
LEFT_COIN_AUDIT_NUM,
RIGHT_COIN_AUDIT_NUM,
BILLS_COIN_AUDIT_NUM,
CENTER_COIN_AUDIT_NUM,
EXTRA_COIN_AUDIT_NUM,
GAME_START_AUD,
MID_GAME_START_AUD,
CONTINUE_AUD,
CHALLENGER_ACCEPTED_AUD,
FREE_QUARTERS_AUD,
FREE_GAME_AUD,
SERVICE_CREDITS_AUD,
TOTAL_PLAYS_AUD,
TOTAL_PAID_CREDITS_AUD,
TOTAL_MONEY_AUDIT_NUM,
};


// Table used to clear the credits audits
static int	credits_audits[] = {
CREDITS_AUD,
};


// Table used to clear out game audits
static int	game_audits[] = {
	NUM_MACHINE_POWER_ON_AUD,
	UPTIME_AUDIT_NUM,
	PLAYTIME_AUD,
	PLAYTIME_PERCENT_AUD,
	FULL_GAME_PURCHASE_AUD,
	FULL_GAME_PURCHASE_PCT_AUD,
	INITIALS_ENTERED_AUD,
	INITIALS_ENTERED_PERCENT_AUD,
	CREATE_PLAYER_AUD,
	CREATE_PLAYER_PERCENT_AUD,
	FINISHED_GAMES_AUD,
	QUARTERS_PLAYED_AUD,
	ONE_PLAYER_AUD,
	TWO_PLAYER_AUD,
	THREE_PLAYER_AUD,
	FOUR_PLAYER_AUD,
	TWOVCPU_PLAYER_AUD,
	ONE_PLAYER_PERCENT_AUD,
	TWO_PLAYER_PERCENT_AUD,
	THREE_PLAYER_PERCENT_AUD,
	FOUR_PLAYER_PERCENT_AUD,
	TWOVCPU_PLAYER_PERCENT_AUD,
	ONE_QUARTER_AUD,
	TWO_QUARTER_AUD,
	THREE_QUARTER_AUD,
	FOUR_QUARTER_AUD,
	ONE_OVERTIME_AUD,
	TWO_OVERTIME_AUD,
	THREE_OVERTIME_AUD,
	ONE_QUARTER_PERCENT_AUD,
	TWO_QUARTER_PERCENT_AUD,
	THREE_QUARTER_PERCENT_AUD,
	FOUR_QUARTER_PERCENT_AUD,
	ONE_OVERTIME_PERCENT_AUD,
	TWO_OVERTIME_PERCENT_AUD,
	THREE_OVERTIME_PERCENT_AUD,
	ONE_PLAYER_FINISH_AUD,
	TWO_PLAYER_FINISH_AUD,
	THREE_PLAYER_FINISH_AUD,
	FOUR_PLAYER_FINISH_AUD,
	TWOVCPU_PLAYER_FINISH_AUD,
	ONE_PLAYER_FINISH_PERCENT_AUD,
	TWO_PLAYER_FINISH_PERCENT_AUD,
	THREE_PLAYER_FINISH_PERCENT_AUD,
	FOUR_PLAYER_FINISH_PERCENT_AUD,
	TWOVCPU_PLAYER_FINISH_PERCENT_AUD,
	HVH_FINISH_AUD,
	HVC_FINISH_AUD,
	HVH_FINISH_PERCENT_AUD,
	TOTAL_HVSH_POINTS_AUD,
	TOTAL_HVSC_POINTS_AUD,
	AVERAGE_HVSH_POINTS_AUD,
	AVERAGE_HVSC_POINTS_AUD,
	TOTAL_WINNING_POINTS_AUD,
	TOTAL_LOSING_POINTS_AUD,
	AVERAGE_WINNING_SCORE_AUD,
	AVERAGE_LOSING_SCORE_AUD,
	TOTAL_CPU_VICTORIES_AUD,
	CPU_VICTORY_PERCENT_AUD,
	LARGEST_CPU_VICTORY_AUD,
	LARGEST_CPU_LOSS_AUD,
	LEFT_SIDE_WINS_AUD,
	LEFT_SIDE_WINS_PERCENT_AUD
};


// Table used to clear out team audits
int	team_audits[] = {
	ATLANTA_HAWKS_AUD,
	BOSTON_CELTICS_AUD,
	CHARLOTTE_HORNETS_AUD,
	CHICAGO_BULLS_AUD,
	CLEVLAND_CAVALIERS_AUD,
	DALLAS_MAVERICKS_AUD,
	DENVER_NUGGETS_AUD,
	DETROIT_PISTONS_AUD,
	GOLDEN_STATE_WARRIORS_AUD,
	HOUSTON_ROCKETS_AUD,
	INDIANAPOLIS_PACERS_AUD,
	LOS_ANGELES_CLIPPERS_AUD,
	LOS_ANGELES_LAKERS_AUD,
	MIAMI_HEAT_AUD,
	MILWAUKEE_BUCKS_AUD,
	MINNESOTA_TIMBERWOLVES_AUD,
	NEW_JERSEY_NETS_AUD,
	NEW_YORK_KNICKS_AUD,
	ORLANDO_MAGIC_AUD,
	PHILADELPHIA_SEVENTYSIXERS_AUD,
	PHOENIX_SUNS_AUD,
	PORTLAND_TRAILBLAZERS_AUD,
	SACRAMENTO_KINGS_AUD,
	SAN_ANTONIO_SPURS_AUD,
	SEATTLE_SUPERSONICS_AUD,
	TORONTO_RAPTORS_AUD,
	UTAH_JAZZ_AUD,
	VANCOUVER_GRIZZLIES_AUD,
	WASHINGTON_WIZARDS_AUD,

	ATLANTA_HAWKS_PERCENT_AUD,
	BOSTON_CELTICS_PERCENT_AUD,
	CHARLOTTE_HORNETS_PERCENT_AUD,
	CHICAGO_BULLS_PERCENT_AUD,
	CLEVLAND_CAVALIERS_PERCENT_AUD,
	DALLAS_MAVERICKS_PERCENT_AUD,
	DENVER_NUGGETS_PERCENT_AUD,
	DETROIT_PISTONS_PERCENT_AUD,
	GOLDEN_STATE_WARRIORS_PERCENT_AUD,
	HOUSTON_ROCKETS_PERCENT_AUD,
	INDIANAPOLIS_PACERS_PERCENT_AUD,
	LOS_ANGELES_CLIPPERS_PERCENT_AUD,
	LOS_ANGELES_LAKERS_PERCENT_AUD,
	MIAMI_HEAT_PERCENT_AUD,
	MILWAUKEE_BUCKS_PERCENT_AUD,
	MINNESOTA_TIMBERWOLVES_PERCENT_AUD,
	NEW_JERSEY_NETS_PERCENT_AUD,
	NEW_YORK_KNICKS_PERCENT_AUD,
	ORLANDO_MAGIC_PERCENT_AUD,
	PHILADELPHIA_SEVENTYSIXERS_PERCENT_AUD,
	PHOENIX_SUNS_PERCENT_AUD,
	PORTLAND_TRAILBLAZERS_PERCENT_AUD,
	SACRAMENTO_KINGS_PERCENT_AUD,
	SAN_ANTONIO_SPURS_PERCENT_AUD,
	SEATTLE_SUPERSONICS_PERCENT_AUD,
	TORONTO_RAPTORS_PERCENT_AUD,
	UTAH_JAZZ_PERCENT_AUD,
	VANCOUVER_GRIZZLIES_PERCENT_AUD,
	WASHINGTON_WIZARDS_PERCENT_AUD
};

static int	feature_audits[] = {
	ACTIVE_PLAYER_RECORD_AUD,
	PURGED_RECORD_AUD,
	CREATED_PLAYER_RECORD_PERCENT_AUD,
	TOTAL_PLAYER_FIRE_AUD,
	AVG_PTS_PLAYER_FIRE_AUD,
	TOTAL_TEAM_FIRE_AUD,
	AVG_PTS_TEAM_FIRE_AUD,
	TOTAL_ALLEY_OOPS_AUD,
	TOTAL_DOUBLE_DUNKS_AUD,
	CREATEP_HEAD_MASCOT_PERCENT_AUD,
	CREATEP_HEAD_NBA_STAR_PERCENT_AUD,
	CREATEP_HEAD_FEMALE_PERCENT_AUD,
	CREATEP_HEAD_UM_PERCENT_AUD,
	CREATEP_HEAD_MID_PERCENT_AUD,
	CREATEP_HEAD_OTHER_PERCENT_AUD,
	CREATEP_UNIFORM_DEFAULT_PERCENT_AUD,
	CREATEP_UNIFORM_CUSTOM_PERCENT_AUD,
	CREATEP_UNIFORM_TEAM_PERCENT_AUD,
	CREATEP_NICKNAME_AUD_PERCENT,
	CREATEP_HEIGHT_AVG_AUD,
	CREATEP_WEIGHT_AVG_AUD,
	CREATEP_POWER_AVG_AUD,
	CREATEP_SPEED_AVG_AUD,
	CREATEP_TWOPTS_AVG_AUD,
	CREATEP_THREEPTS_AVG_AUD,
	CREATEP_STEAL_AVG_AUD,
	CREATEP_BLOCK_AVG_AUD,
	CREATEP_DUNKS_AVG_AUD,
	CREATEP_DRIBBLE_AVG_AUD,
	CREATEP_PRIV1_PERCENT_AUD,
	CREATEP_PRIV2_PERCENT_AUD,
	CREATEP_PRIV3_PERCENT_AUD,
	CREATEP_PRIV4_PERCENT_AUD,
	CREATEP_PRIV5_PERCENT_AUD,
	CREATEP_PRIV6_PERCENT_AUD,
	CREATEP_PRIV7_PERCENT_AUD,
	CREATEP_PRIV8_PERCENT_AUD,
	GAMES_PLAYED_WITH_CREATEP_PERCENT_AUD,
	WIN_VCPU_WITH_CREATEP_PRECENT_AUD,
	WIN_VHUM_WITH_CREATEP_PRECENT_AUD,
	GAME_IN_TOURNEY_MODE_PRECENT_AUD,
	UNLOCK_LEVEL_AUD,
	TEX_LOAD_FAIL_AUD,
	SND_LOAD_FAIL_AUD
};

void write_audit_info(FILE *fp)
{
	// Coin Audits
	ADD_MENU_ITEM("COIN AUDITS", "SHOW THE COINS TAKEN");

	// Audits on the coin page(s)
	ADD_AUDIT(LEFT_COIN_AUDIT_NUM, MEDIUM_FONT, LT_YELLOW, "LEFT SLOT COINS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(RIGHT_COIN_AUDIT_NUM, MEDIUM_FONT, LT_CYAN, "RIGHT SLOT COINS", DECIMAL, LT_CYAN);
	ADD_AUDIT(BILLS_COIN_AUDIT_NUM, MEDIUM_FONT, LT_YELLOW, "BILLS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CENTER_COIN_AUDIT_NUM, MEDIUM_FONT, LT_CYAN, "CENTER SLOT COINS", DECIMAL, LT_CYAN);
	ADD_AUDIT(EXTRA_COIN_AUDIT_NUM, MEDIUM_FONT, LT_YELLOW, "EXTRA SLOT COINS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(GAME_START_AUD, MEDIUM_FONT, LT_CYAN, "GAME STARTS", DECIMAL, LT_CYAN);
	ADD_AUDIT(MID_GAME_START_AUD, MEDIUM_FONT, LT_YELLOW, "MID-GAME STARTS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CONTINUE_AUD, MEDIUM_FONT, LT_CYAN, "CONTINUES", DECIMAL, LT_CYAN);
	ADD_AUDIT(CHALLENGER_ACCEPTED_AUD, MEDIUM_FONT, LT_YELLOW, "CHALLENGER ACCEPTED", DECIMAL, LT_YELLOW);
	ADD_AUDIT(FREE_QUARTERS_AUD, MEDIUM_FONT, LT_CYAN, "FREE QUARTERS AWARDED", DECIMAL, LT_CYAN);
	ADD_AUDIT(FREE_GAME_AUD, MEDIUM_FONT, LT_YELLOW, "FREE GAMES AWARDED", DECIMAL, LT_YELLOW);
	ADD_AUDIT(SERVICE_CREDITS_AUD, MEDIUM_FONT, LT_CYAN, "SERVICE CREDITS", DECIMAL, LT_CYAN);
	ADD_AUDIT(TOTAL_PLAYS_AUD, MEDIUM_FONT, LT_YELLOW, "TOTAL PLAYS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(TOTAL_PAID_CREDITS_AUD, MEDIUM_FONT, LT_CYAN, "TOTAL PAID CREDITS", DECIMAL, LT_CYAN);
	ADD_AUDIT(TOTAL_MONEY_AUDIT_NUM, LARGE_FONT, LT_YELLOW, "TOTAL", MONEY, LT_YELLOW);


	// Credits Audits
	ADD_MENU_ITEM("CREDITS AUDITS", "SHOW THE AVAILABLE CREDITS");

	// Audits on the credits page
	ADD_AUDIT(CREDITS_AUD, LARGE_FONT, LT_YELLOW, "CREDITS AVAILABLE", DECIMAL, WHITE);


	// Game Audits
	ADD_MENU_ITEM("GAME AUDITS", "SHOW STATISTICS ABOUT THE GAME");
	COLUMNS(2);	

	// Audits on the game page(s)
	ADD_AUDIT(NUM_MACHINE_POWER_ON_AUD, SMALL_FONT, LT_YELLOW, "MACHINE POWER-ON", DECIMAL, LT_YELLOW);
	ADD_AUDIT(UPTIME_AUDIT_NUM, SMALL_FONT, LT_CYAN, "TOTAL UPTIME", DURATION, LT_CYAN);
	ADD_AUDIT(PLAYTIME_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "TOTAL PLAYTIME", PERCENT, LT_YELLOW);
	ADD_AUDIT(GAME_START_AUD, SMALL_FONT, LT_CYAN, "GAMES STARTED", DECIMAL, LT_CYAN);
	ADD_AUDIT(INITIALS_ENTERED_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "INITIALS ENTERED", PERCENT, LT_YELLOW);
	ADD_AUDIT(FULL_GAME_PURCHASE_PCT_AUD, SMALL_FONT, LT_CYAN, "(FG) PURCHASED AT START", PERCENT, LT_CYAN);

	ADD_AUDIT(CREATE_PLAYER_AUD, SMALL_FONT, LT_YELLOW, "CREATE PLAYER SESSIONS", DECIMAL, LT_YELLOW );
	ADD_AUDIT(ONE_PLAYER_PERCENT_AUD, SMALL_FONT, LT_CYAN, "1 PLAYER", PERCENT, LT_CYAN);
	ADD_AUDIT(TWO_PLAYER_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "2 PLAYER", PERCENT, LT_YELLOW);
	ADD_AUDIT(THREE_PLAYER_PERCENT_AUD, SMALL_FONT, LT_CYAN, "3 PLAYER", PERCENT, LT_CYAN);
	ADD_AUDIT(FOUR_PLAYER_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "4 PLAYER", PERCENT, LT_YELLOW);

	ADD_AUDIT(TWOVCPU_PLAYER_PERCENT_AUD, SMALL_FONT, LT_CYAN, "2P V CPU", PERCENT, LT_CYAN);
	ADD_AUDIT(ONE_QUARTER_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "1 QUARTER GAMES", PERCENT, LT_YELLOW);
	ADD_AUDIT(TWO_QUARTER_PERCENT_AUD, SMALL_FONT, LT_CYAN, "2 QUARTER GAMES", PERCENT, LT_CYAN);
	ADD_AUDIT(THREE_QUARTER_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "3 QUARTER GAMES", PERCENT, LT_YELLOW);
	ADD_AUDIT(FOUR_QUARTER_PERCENT_AUD, SMALL_FONT, LT_CYAN, "4 QUARTER GAMES", PERCENT, LT_CYAN);
	ADD_AUDIT(ONE_OVERTIME_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "WENT INTO OVERTIME 1", PERCENT, LT_YELLOW);
	ADD_AUDIT(TWO_OVERTIME_PERCENT_AUD, SMALL_FONT, LT_CYAN, "WENT INTO OVERTIME 2", PERCENT, LT_CYAN);
	ADD_AUDIT(THREE_OVERTIME_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "WENT INTO OVERTIME 3", PERCENT, LT_YELLOW);

	ADD_AUDIT(ONE_PLAYER_FINISH_PERCENT_AUD, SMALL_FONT, LT_CYAN, "1 PLAYER FINISHES", PERCENT, LT_CYAN);
	ADD_AUDIT(TWO_PLAYER_FINISH_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "2 PLAYER FINISHES", PERCENT, LT_YELLOW);
	ADD_AUDIT(THREE_PLAYER_FINISH_PERCENT_AUD, SMALL_FONT, LT_CYAN, "3 PLAYER FINISHES", PERCENT, LT_CYAN);
	ADD_AUDIT(FOUR_PLAYER_FINISH_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "4 PLAYER FINISHES", PERCENT, LT_YELLOW);
	ADD_AUDIT(TWOVCPU_PLAYER_FINISH_PERCENT_AUD, SMALL_FONT, LT_CYAN, "2P V CPU FINISHES", PERCENT, LT_CYAN);

	ADD_AUDIT(LEFT_SIDE_WINS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "H VS H LSW'S", PERCENT, LT_YELLOW);
	ADD_AUDIT(CPU_VICTORY_PERCENT_AUD, SMALL_FONT, LT_CYAN, "CPU WINS (FG)", PERCENT, LT_CYAN);

	ADD_AUDIT(AVERAGE_HVSH_POINTS_AUD, SMALL_FONT, LT_YELLOW, "AVG H VS H TOTAL SCORE (FG)", DECIMAL, LT_YELLOW);
	ADD_AUDIT(AVERAGE_HVSC_POINTS_AUD, SMALL_FONT, LT_CYAN, "AVG H VS CPU TOTAL SCORE (FG)", DECIMAL, LT_CYAN);
	ADD_AUDIT(AVERAGE_WINNING_SCORE_AUD, SMALL_FONT, LT_YELLOW, "AVG H VS H WIN SCORE (FG)", DECIMAL, LT_YELLOW);
	ADD_AUDIT(AVERAGE_LOSING_SCORE_AUD, SMALL_FONT, LT_CYAN, "AVG H VS H LOSS SCORE (FG)", DECIMAL, LT_CYAN);
	ADD_AUDIT(LARGEST_CPU_VICTORY_AUD, SMALL_FONT, LT_YELLOW, "BIGGEST CPU WIN MARGIN (FG)", DECIMAL, LT_YELLOW);
	ADD_AUDIT(LARGEST_CPU_LOSS_AUD, SMALL_FONT, LT_CYAN, "BIGGEST CPU LOSS MARGIN (FG)", DECIMAL, LT_CYAN);

	// team stats
	ADD_MENU_ITEM("TEAM STATS", "SHOW STATISTICS ABOUT EACH NFL TEAM");
	COLUMNS(2);	
	ADD_AUDIT(ATLANTA_HAWKS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "ATLANTA HAWKS", PERCENT, LT_YELLOW);
	ADD_AUDIT(BOSTON_CELTICS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "BOSTON CELTICS", PERCENT, LT_CYAN);
	ADD_AUDIT(CHARLOTTE_HORNETS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "CHARLOTTE HORNETS", PERCENT, LT_YELLOW);
	ADD_AUDIT(CHICAGO_BULLS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "CHICAGO BULLS", PERCENT, LT_CYAN);
	ADD_AUDIT(CLEVLAND_CAVALIERS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "CLEVLAND CAVALIERS", PERCENT, LT_YELLOW);
	ADD_AUDIT(DALLAS_MAVERICKS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "DALLAS MAVERICKS", PERCENT, LT_CYAN);
	ADD_AUDIT(DENVER_NUGGETS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "DENVER NUGGETS", PERCENT, LT_YELLOW);
	ADD_AUDIT(DETROIT_PISTONS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "DETROIT PISTONS", PERCENT, LT_CYAN);
	ADD_AUDIT(GOLDEN_STATE_WARRIORS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "GOLDEN STATE WARRIORS", PERCENT, LT_YELLOW);
	ADD_AUDIT(HOUSTON_ROCKETS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "HOUSTON ROCKETS", PERCENT, LT_CYAN);
	ADD_AUDIT(INDIANAPOLIS_PACERS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "INDIANAPOLIS PACERS", PERCENT, LT_YELLOW);
	ADD_AUDIT(LOS_ANGELES_CLIPPERS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "LOS ANGELES CLIPPERS", PERCENT, LT_CYAN);
	ADD_AUDIT(LOS_ANGELES_LAKERS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "LOS ANGELES LAKERS", PERCENT, LT_YELLOW);
	ADD_AUDIT(MIAMI_HEAT_PERCENT_AUD, SMALL_FONT, LT_CYAN, "MIAMI HEAT", PERCENT, LT_CYAN);
	ADD_AUDIT(MILWAUKEE_BUCKS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "MILWAUKEE BUCKS", PERCENT, LT_YELLOW);
	ADD_AUDIT(MINNESOTA_TIMBERWOLVES_PERCENT_AUD, SMALL_FONT, LT_CYAN, "MINNESOTA TIMBERWOLVES", PERCENT, LT_CYAN);
	ADD_AUDIT(NEW_JERSEY_NETS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "NEW JERSEY NETS", PERCENT, LT_YELLOW);
	ADD_AUDIT(NEW_YORK_KNICKS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "NEW YORK KNICKS", PERCENT, LT_CYAN);
	ADD_AUDIT(ORLANDO_MAGIC_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "ORLANDO MAGIC", PERCENT, LT_YELLOW);
	ADD_AUDIT(PHILADELPHIA_SEVENTYSIXERS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "PHILADELPHIA 76ERS", PERCENT, LT_CYAN);
	ADD_AUDIT(PHOENIX_SUNS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "PHOENIX SUNS", PERCENT, LT_YELLOW);
	ADD_AUDIT(PORTLAND_TRAILBLAZERS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "PORTLAND TRAILBLAZERS", PERCENT, LT_CYAN);
	ADD_AUDIT(SACRAMENTO_KINGS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "SACRAMENTO KINGS", PERCENT, LT_YELLOW);
	ADD_AUDIT(SAN_ANTONIO_SPURS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "SAN ANTONIO SPURS", PERCENT, LT_CYAN);
	ADD_AUDIT(SEATTLE_SUPERSONICS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "SEATTLE SUPERSONICS", PERCENT, LT_YELLOW);
	ADD_AUDIT(TORONTO_RAPTORS_PERCENT_AUD, SMALL_FONT, LT_CYAN, "TORONTO RAPTORS", PERCENT, LT_CYAN);
	ADD_AUDIT(UTAH_JAZZ_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "UTAH JAZZ", PERCENT, LT_YELLOW);
	ADD_AUDIT(VANCOUVER_GRIZZLIES_PERCENT_AUD, SMALL_FONT, LT_CYAN, "VANCOUVER GRIZZLIES", PERCENT, LT_CYAN);
	ADD_AUDIT(WASHINGTON_WIZARDS_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "WASHINGTON WIZARDS", PERCENT, LT_YELLOW);

	// Features
	ADD_MENU_ITEM("GAME FEATURES", "SHOW GAME STATISTICS");
	COLUMNS(2);	
	ADD_AUDIT(ACTIVE_PLAYER_RECORD_AUD, SMALL_FONT, LT_YELLOW, "NUMBER OF PLAYER RECORDS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(PURGED_RECORD_AUD, SMALL_FONT, LT_CYAN, "NUMBER OF LRU RECORDS", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATED_PLAYER_RECORD_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "RECORDS FROM CREATE PLAYER", PERCENT, LT_YELLOW);
	ADD_AUDIT(TOTAL_PLAYER_FIRE_AUD, SMALL_FONT, LT_CYAN, "NUMBER OF PLAYER FIRE", DECIMAL, LT_CYAN);
	ADD_AUDIT(AVG_PTS_PLAYER_FIRE_AUD, SMALL_FONT, LT_YELLOW, "AVG PTS PLAYER FIRE", DECIMAL, LT_YELLOW);
	ADD_AUDIT(TOTAL_TEAM_FIRE_AUD, SMALL_FONT, LT_CYAN, "NUMBER OF TEAM FIRE", DECIMAL, LT_CYAN);
	ADD_AUDIT(AVG_PTS_TEAM_FIRE_AUD, SMALL_FONT, LT_YELLOW, "AVG PTS TEAM FIRE", DECIMAL, LT_YELLOW);
	ADD_AUDIT(TOTAL_ALLEY_OOPS_AUD, SMALL_FONT, LT_CYAN, "NUMBER OF ALLEY OOPS", DECIMAL, LT_CYAN);
	ADD_AUDIT(TOTAL_DOUBLE_DUNKS_AUD, SMALL_FONT, LT_YELLOW, "NUMBER OF DOUBLE DUNKS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CREATEP_HEAD_MASCOT_PERCENT_AUD, SMALL_FONT, LT_CYAN, "CREATP MASCOT HEADS", PERCENT, LT_CYAN);
	ADD_AUDIT(CREATEP_HEAD_NBA_STAR_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "CREATP NBA HEADS", PERCENT, LT_YELLOW);
	ADD_AUDIT(CREATEP_HEAD_FEMALE_PERCENT_AUD, SMALL_FONT, LT_CYAN, "CREATP FEMALE HEADS", PERCENT, LT_CYAN);
	ADD_AUDIT(CREATEP_HEAD_UM_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "CREATP UM HEADS", PERCENT, LT_YELLOW);
	ADD_AUDIT(CREATEP_HEAD_MID_PERCENT_AUD, SMALL_FONT, LT_CYAN, "CREATP MID HEADS", PERCENT, LT_CYAN);
	ADD_AUDIT(CREATEP_HEAD_OTHER_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "CREATP OTHER HEADS", PERCENT, LT_YELLOW);
	ADD_AUDIT(CREATEP_UNIFORM_DEFAULT_PERCENT_AUD, SMALL_FONT, LT_CYAN, "CREATP DEFAULT UNIFORM", PERCENT, LT_CYAN);
	ADD_AUDIT(CREATEP_UNIFORM_CUSTOM_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "CREATP CUSTOM UNIFORM", PERCENT, LT_YELLOW);
	ADD_AUDIT(CREATEP_UNIFORM_TEAM_PERCENT_AUD, SMALL_FONT, LT_CYAN, "CREATP TEAM UNIFORM", PERCENT, LT_CYAN);
	ADD_AUDIT(CREATEP_NICKNAME_AUD_PERCENT, SMALL_FONT, LT_YELLOW, "CREATP NICKNAME", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CREATEP_HEIGHT_AVG_AUD, SMALL_FONT, LT_CYAN, "CREATP AVG HEIGHT PTS", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATEP_WEIGHT_AVG_AUD, SMALL_FONT, LT_YELLOW, "CREATP AVG WEIGHT PTS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CREATEP_POWER_AVG_AUD, SMALL_FONT, LT_CYAN, "CREATP AVG POWER PTS", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATEP_SPEED_AVG_AUD, SMALL_FONT, LT_YELLOW, "CREATP AVG SPEED PTS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CREATEP_TWOPTS_AVG_AUD, SMALL_FONT, LT_CYAN, "CREATP AVG TWOPTS PTS", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATEP_THREEPTS_AVG_AUD, SMALL_FONT, LT_YELLOW, "CREATP AVG THREEPTS PTS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CREATEP_STEAL_AVG_AUD, SMALL_FONT, LT_CYAN, "CREATP AVG STEAL PTS", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATEP_BLOCK_AVG_AUD, SMALL_FONT, LT_YELLOW, "CREATP AVG BLOCK PTS", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CREATEP_DUNKS_AVG_AUD, SMALL_FONT, LT_CYAN, "CREATP AVG DUNK PTS", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATEP_DRIBBLE_AVG_AUD, SMALL_FONT, LT_YELLOW, "CREATP AVG DRIBBLE PTS", DECIMAL, LT_YELLOW);

	ADD_AUDIT(CREATEP_PRIV1_PERCENT_AUD, SMALL_FONT, LT_CYAN, "PRIV1", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATEP_PRIV2_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "PRIV2", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CREATEP_PRIV3_PERCENT_AUD, SMALL_FONT, LT_CYAN, "PRIV3", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATEP_PRIV4_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "PRIV4", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CREATEP_PRIV5_PERCENT_AUD, SMALL_FONT, LT_CYAN, "PRIV5", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATEP_PRIV6_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "PRIV6", DECIMAL, LT_YELLOW);
	ADD_AUDIT(CREATEP_PRIV7_PERCENT_AUD, SMALL_FONT, LT_CYAN, "PRIV7", DECIMAL, LT_CYAN);
	ADD_AUDIT(CREATEP_PRIV8_PERCENT_AUD, SMALL_FONT, LT_YELLOW, "PRIV8", DECIMAL, LT_YELLOW);

	ADD_AUDIT(GAMES_PLAYED_WITH_CREATEP_PERCENT_AUD, SMALL_FONT, LT_CYAN, "GAME WITH CREATP", DECIMAL, LT_CYAN);
	ADD_AUDIT(WIN_VCPU_WITH_CREATEP_PRECENT_AUD, SMALL_FONT, LT_YELLOW, "WIN V CPU WITH CREATP", DECIMAL, LT_YELLOW);
	ADD_AUDIT(WIN_VHUM_WITH_CREATEP_PRECENT_AUD, SMALL_FONT, LT_CYAN, "WIN V HUMAN WITH CREATP", DECIMAL, LT_CYAN);
	ADD_AUDIT(GAME_IN_TOURNEY_MODE_PRECENT_AUD, SMALL_FONT, LT_YELLOW, "TOURNAMENT GAMES", DECIMAL, LT_YELLOW);
	ADD_AUDIT(UNLOCK_LEVEL_AUD, SMALL_FONT, LT_CYAN, "TIMER LEVEL", DECIMAL, LT_CYAN);

	ADD_AUDIT(TEX_LOAD_FAIL_AUD, SMALL_FONT, LT_YELLOW, "TLF'S", DECIMAL, LT_YELLOW);
	ADD_AUDIT(SND_LOAD_FAIL_AUD, SMALL_FONT, LT_CYAN, "SBLF'S", DECIMAL, LT_CYAN);
}

static void clear_aud(int num, int *table)
{
	int	val;

	while(num--)
	{
		set_audit(*table, 0);
		if(get_audit(*table, &val))
		{
#ifdef DEBUG
			fprintf(stderr, "Trouble clear audit number: %d\r\n", *table);
			lockup();
#endif
			return;
		}
		++table;
	}
}
			
void clear_coin_audits(void)
{
	clear_aud(sizeof(coin_audits)/sizeof(int), coin_audits);
}

void clear_credits_audits(void)
{
	clear_aud(sizeof(credits_audits)/sizeof(int), credits_audits);
}

void clear_game_audits(void)
{
	clear_aud(sizeof(game_audits)/sizeof(int), game_audits);
}

void clear_team_audits(void)
{
	clear_aud(sizeof(team_audits)/sizeof(int), team_audits);
}

void clear_feature_audits(void)
{
	clear_aud(sizeof(feature_audits)/sizeof(int), feature_audits);
}

void clear_all_audits(void)
{
	clear_coin_audits();
	clear_credits_audits();
	clear_game_audits();
	clear_team_audits();
	clear_feature_audits();
}

static int check_aud(int num, int *table)
{
	int	val;

	while(num--)
	{
		if(get_audit(*table, &val))
		{
			set_audit(*table, 0);
			if(get_audit(*table, &val))
			{
#ifdef DEBUG
				fprintf(stderr, "Trouble with audit number: %d\r\n", *table);
				lockup();
#endif
				return(0);
			}
		}
		++table;
	}
	return(1);
}

int check_coin_audits(void)
{
	return(check_aud(sizeof(coin_audits)/sizeof(int), coin_audits));
}

int check_credits_audits(void)
{
	return(check_aud(sizeof(credits_audits)/sizeof(int), credits_audits));
}

int check_game_audits(void)
{
	return(check_aud(sizeof(game_audits)/sizeof(int), game_audits));
}

int check_team_audits(void)
{
	return(check_aud(sizeof(team_audits)/sizeof(int), team_audits));
}

int check_feature_audits(void)
{
	return(check_aud(sizeof(feature_audits)/sizeof(int), feature_audits));
}

int check_all_audits(void)
{
	int	status = 1;

	if(!check_coin_audits())
	{
		status = 0;
	}

	if(!check_credits_audits())
	{
		status = 0;
	}

	if(!check_game_audits())
	{
		status = 0;
	}

	if(!check_team_audits())
	{
		status = 0;
	}

	if(!check_feature_audits())
	{
		status = 0;
	}

	return(status);
}


void do_percent_aud(int naud, int daud, int paud)
{
	int	divis;
	int	nom;

	increment_audit(naud);
	if(!(get_audit(daud, &divis)))
	{
		if(divis > 0)
		{
			get_audit(naud, &nom);
			nom *= 100;
			nom /= divis;
			set_audit(paud, nom);
		}
	}
}

void recalc_percent_aud(int naud, int daud, int paud)
{
	int	divis;
	int	nom;

	if(!(get_audit(daud, &divis)))
	{
		if(divis > 0)
		{
			get_audit(naud, &nom);
			nom *= 100;
			nom /= divis;
			set_audit(paud, nom);
		}
	}
}

static int get_aud_total(int saud, int eaud)
{
	int	i;
	int	divis = 0;
	int	val;

	for(i = saud; i <= eaud; i++)
	{
		if(get_audit(i, &val))
		{
			val = 0;
		}
		divis += val;
	}
	return(divis);
}

static void calc_team_aud_percent(int aud, int divis)
{
	int	i;
	int	nom;
	int	val;

	if(get_audit(aud, &nom))
	{
		nom = 0;
	}

	if(!divis)
	{
		set_audit(aud+(ATLANTA_HAWKS_PERCENT_AUD-ATLANTA_HAWKS_AUD), 0);
		return;
	}

	nom *= 100;
	nom /= divis;

	set_audit(aud+(ATLANTA_HAWKS_PERCENT_AUD-ATLANTA_HAWKS_AUD), nom);
}


void do_team_percent_aud(int aud)
{
	int	i;
	int	divis;

	increment_audit(aud);
	divis = get_aud_total(ATLANTA_HAWKS_AUD, WASHINGTON_WIZARDS_AUD);
	for(i = ATLANTA_HAWKS_AUD; i <= WASHINGTON_WIZARDS_AUD; i++)
	{
		calc_team_aud_percent(i, divis);
	}
}

/*
** add_to_audit() - This function is used to add to the value
** of an audit.
*/
int add_to_audit(int audit_number, int val)
{
	int	old_val;
	int	status;

	old_val = audit_number;
	status = get_audit(audit_number, &old_val);
	if(status != CMOS_OK)
	{
		return(status);
	}
	old_val += val;
	return(set_audit(audit_number, old_val));
}

/*
** decrement_audit() - This function is used to decrement the value of an
** audit.
*/
int decrement_audit(int audit_number)
{
	int	old_val;
	int	status;

	old_val = audit_number;
	status = get_audit(audit_number, &old_val);
	if(status != CMOS_OK)
	{
		return(status);
	}
	old_val--;
	return(set_audit(audit_number, old_val));
}

/*
** get_audit_val() - Returns the value of an audit. (No error checking)
*/
int get_audit_val( int audit_number )
{
	int		val;

	get_audit( audit_number, &val );

	return val;
}
