/*
 *		$Archive: /video/Nba/data.c $
 *		$Revision: 41 $
 *		$Date: 4/05/99 5:05p $
 *
 *		Copyright (c) 1997, 1998 Midway Games Inc.
 *		All Rights Reserved
 *
 *		This file is confidential and a trade secret of Midway Games Inc.
 *		Use, reproduction, adaptation, distribution, performance or
 *		display of this computer program or the associated audiovisual work
 *		is strictly forbidden unless approved in writing by Midway Games Inc.
 */

#ifdef INCLUDE_SSID
char *ss_data_c = "$Workfile: data.c $ $Revision: 41 $";
#endif

/*
 *		USER INCLUDES
 */

#include "include/ani3D.h"

#include "models/gndsqr.h"
#include "models/ballshad.h"

#include "models/spfx.h"
#include "models/BBall.h"
#include "models/BBallhlt.h"
#include "models/BBalShde.h"

#include "models/nt_swish.h"
#include "models/nt_swshb.h"
#include "models/nt_hard.h"
#include "models/nt_rim.h"
#include "models/nt_dunk.h"
#include "models/nt_air.h"

// PLAYER HANDS
#include "models/fist_r1.h"
#include "models/fist_l1.h"
#include "models/hand_r1.h"
#include "models/hand_l1.h"
#include "models/ohand_r2.h"
#include "models/ohand_l2.h"
#include "models/fhand_r.h"
#include "models/fhand_l.h"

// JERSEY NUMBERS
#include "models/jn_1.h"
#include "models/jn_2.h"

// ALIEN CHARACTER
#include "models/waist_a.h"
#include "models/torso_a.h"
#include "models/arm_ula.h"
#include "models/arm_ura.h"
#include "models/arm_lla.h"
#include "models/arm_lra.h"
#include "models/hand_ra.h"
#include "models/hand_la.h"
#include "models/leg_ula.h"
#include "models/leg_ura.h"
#include "models/leg_lla.h"
#include "models/leg_lra.h"
#include "models/foot_ra.h"
#include "models/foot_la.h"

// SPACE JAM CHARACTER
#include "models/waist_j.h"
#include "models/torso_j.h"
#include "models/arm_ulj.h"
#include "models/arm_urj.h"
#include "models/arm_llj.h"
#include "models/arm_lrj.h"
#include "models/hand_rj.h"
#include "models/hand_lj.h"
#include "models/leg_ulj.h"
#include "models/leg_urj.h"
#include "models/leg_llj.h"
#include "models/leg_lrj.h"
#include "models/foot_rj.h"
#include "models/foot_lj.h"

// NIKKO DOG CHARACTER
#include "models/waist_n.h"
#include "models/torso_n.h"
#include "models/arm_uln.h"
#include "models/arm_urn.h"
#include "models/arm_lln.h"
#include "models/arm_lrn.h"
#include "models/hand_rn.h"
#include "models/hand_ln.h"
#include "models/leg_uln.h"
#include "models/leg_urn.h"
#include "models/leg_lln.h"
#include "models/leg_lrn.h"
#include "models/foot_rn.h"
#include "models/foot_ln.h"


// HORNETS MASCOT
#include "models/waist_h.h"
#include "models/torso_h.h"
#include "models/arm_ulh.h"
#include "models/arm_urh.h"
#include "models/arm_llh.h"
#include "models/arm_lrh.h"
#include "models/hand_rh.h"
#include "models/hand_lh.h"
#include "models/leg_ulh.h"
#include "models/leg_urh.h"
#include "models/leg_llh.h"
#include "models/leg_lrh.h"
#include "models/foot_rh.h"
#include "models/foot_lh.h"

// PACERS MASCOT
#include "models/waist_b.h"
#include "models/torso_b.h"
#include "models/arm_ulb.h"
#include "models/arm_urb.h"
#include "models/arm_llb.h"
#include "models/arm_lrb.h"
#include "models/hand_rb.h"
#include "models/hand_lb.h"
#include "models/leg_ulb.h"
#include "models/leg_urb.h"
#include "models/leg_llb.h"
#include "models/leg_lrb.h"
#include "models/foot_rb.h"
#include "models/foot_lb.h"

// TIMBERWOLVES MASCOT
#include "models/waist_c.h"
#include "models/torso_c.h"
#include "models/arm_ulc.h"
#include "models/arm_urc.h"
#include "models/arm_llc.h"
#include "models/arm_lrc.h"
#include "models/hand_rc.h"
#include "models/hand_lc.h"
#include "models/leg_ulc.h"
#include "models/leg_urc.h"
#include "models/leg_llc.h"
#include "models/leg_lrc.h"
#include "models/foot_rc.h"
#include "models/foot_lc.h"

// RAPTORS MASCOT
#include "models/waist_r.h"
#include "models/torso_r.h"
#include "models/arm_ulr.h"
#include "models/arm_urr.h"
#include "models/arm_llr.h"
#include "models/arm_lrr.h"
#include "models/hand_rr.h"
#include "models/hand_lr.h"
#include "models/leg_ulr.h"
#include "models/leg_urr.h"
#include "models/leg_llr.h"
#include "models/leg_lrr.h"
#include "models/foot_rr.h"
#include "models/foot_lr.h"

// BULLS MASCOT
#include "models/waist_cb.h"
#include "models/torso_cb.h"
#include "models/arm_ulcb.h"
#include "models/arm_urcb.h"
#include "models/arm_llcb.h"
#include "models/arm_lrcb.h"
#include "models/hand_rcb.h"
#include "models/hand_lcb.h"
#include "models/leg_ulcb.h"
#include "models/leg_urcb.h"
#include "models/leg_llcb.h"
#include "models/leg_lrcb.h"
#include "models/foot_rcb.h"
#include "models/foot_lcb.h"

// ROCKETS MASCOT
#include "models/waist_hb.h"
#include "models/torso_hb.h"
#include "models/arm_ulhb.h"
#include "models/arm_urhb.h"
#include "models/arm_llhb.h"
#include "models/arm_lrhb.h"
#include "models/hand_rhb.h"
#include "models/hand_lhb.h"
#include "models/leg_ulhb.h"
#include "models/leg_urhb.h"
#include "models/leg_llhb.h"
#include "models/leg_lrhb.h"
#include "models/foot_rhb.h"
#include "models/foot_lhb.h"

// HAWKS MASCOT
#include "models/waist_ah.h"
#include "models/torso_ah.h"
#include "models/arm_ulah.h"
#include "models/arm_urah.h"
#include "models/arm_llah.h"
#include "models/arm_lrah.h"
#include "models/hand_rah.h"
#include "models/hand_lah.h"
#include "models/leg_ulah.h"
#include "models/leg_urah.h"
#include "models/leg_llah.h"
#include "models/leg_lrah.h"
#include "models/foot_rah.h"
#include "models/foot_lah.h"

// SUNS MASCOT
#include "models/waist_pg.h"
#include "models/torso_pg.h"
#include "models/arm_ulpg.h"
#include "models/arm_urpg.h"
#include "models/arm_llpg.h"
#include "models/arm_lrpg.h"
#include "models/hand_rpg.h"
#include "models/hand_lpg.h"
#include "models/leg_ulpg.h"
#include "models/leg_urpg.h"
#include "models/leg_llpg.h"
#include "models/leg_lrpg.h"
#include "models/foot_rpg.h"
#include "models/foot_lpg.h"

// NETS MASCOT
#include "models/waist_s.h"
#include "models/torso_s.h"
#include "models/arm_uls.h"
#include "models/arm_urs.h"
#include "models/arm_lls.h"
#include "models/arm_lrs.h"
#include "models/hand_rs.h"
#include "models/hand_ls.h"
#include "models/leg_uls.h"
#include "models/leg_urs.h"
#include "models/leg_lls.h"
#include "models/leg_lrs.h"
#include "models/foot_rs.h"
#include "models/foot_ls.h"

// LIA CHARACTER
#include "models/waist_f.h"
#include "models/torso_f.h"
#include "models/arm_ulf.h"
#include "models/arm_urf.h"
#include "models/arm_llf.h"
#include "models/arm_lrf.h"
#include "models/hand_rf.h"
#include "models/hand_lf.h"
#include "models/leg_ulf.h"
#include "models/leg_urf.h"
#include "models/leg_llf.h"
#include "models/leg_lrf.h"
#include "models/foot_rf.h"
#include "models/foot_lf.h"

// RETRO CHARACTER
#include "models/waist_rt.h"
#include "models/torso_rt.h"
#include "models/arm_ulrt.h"
#include "models/arm_urrt.h"
#include "models/arm_llrt.h"
#include "models/arm_lrrt.h"
#include "models/hand_rrt.h"
#include "models/hand_lrt.h"
#include "models/leg_ulrt.h"
#include "models/leg_urrt.h"
#include "models/leg_llrt.h"
#include "models/leg_lrrt.h"
#include "models/foot_rrt.h"
#include "models/foot_lrt.h"

// WIZARD CHARACTER
#include "models/waist_w.h"
#include "models/torso_w.h"
#include "models/arm_ulw.h"
#include "models/arm_urw.h"
#include "models/arm_llw.h"
#include "models/arm_lrw.h"
#include "models/hand_rw.h"
#include "models/hand_lw.h"
#include "models/leg_ulw.h"
#include "models/leg_urw.h"
#include "models/leg_llw.h"
#include "models/leg_lrw.h"
#include "models/foot_rw.h"
#include "models/foot_lw.h"

// OLDMAN CHARACTER
#include "models/waist_om.h"
#include "models/torso_om.h"
#include "models/arm_ulom.h"
#include "models/arm_urom.h"
#include "models/arm_llom.h"
#include "models/arm_lrom.h"
#include "models/hand_rom.h"
#include "models/hand_lom.h"
#include "models/leg_ulom.h"
#include "models/leg_urom.h"
#include "models/leg_llom.h"
#include "models/leg_lrom.h"
#include "models/foot_rom.h"
#include "models/foot_lom.h"

// SONICS MASCOT
#include "models/waist_ss.h"
#include "models/torso_ss.h"
#include "models/arm_ulss.h"
#include "models/arm_urss.h"
#include "models/arm_llss.h"
#include "models/arm_lrss.h"
#include "models/hand_rss.h"
#include "models/hand_lss.h"
#include "models/leg_ulss.h"
#include "models/leg_urss.h"
#include "models/leg_llss.h"
#include "models/leg_lrss.h"
#include "models/foot_rss.h"
#include "models/foot_lss.h"

// CLOWN CHARACTER
#include "models/waist_cc.h"
#include "models/torso_cc.h"
#include "models/arm_ulcc.h"
#include "models/arm_urcc.h"
#include "models/arm_llcc.h"
#include "models/arm_lrcc.h"
#include "models/hand_rcc.h"
#include "models/hand_lcc.h"
#include "models/leg_ulcc.h"
#include "models/leg_urcc.h"
#include "models/leg_llcc.h"
#include "models/leg_lrcc.h"
#include "models/foot_rcc.h"
#include "models/foot_lcc.h"

// PUMPKIN CHARACTER
#include "models/waist_p.h"
#include "models/torso_p.h"
#include "models/arm_ulp.h"
#include "models/arm_urp.h"
#include "models/arm_llp.h"
#include "models/arm_lrp.h"
#include "models/hand_rp.h"
#include "models/hand_lp.h"
#include "models/leg_ulp.h"
#include "models/leg_urp.h"
#include "models/leg_llp.h"
#include "models/leg_lrp.h"
#include "models/foot_rp.h"
#include "models/foot_lp.h"

// DENVER MASCOT
#include "models/waist_dr.h"
#include "models/torso_dr.h"
#include "models/arm_uldr.h"
#include "models/arm_urdr.h"
#include "models/arm_lldr.h"
#include "models/arm_lrdr.h"
#include "models/hand_rdr.h"
#include "models/hand_ldr.h"
#include "models/leg_uldr.h"
#include "models/leg_urdr.h"
#include "models/leg_lldr.h"
#include "models/leg_lrdr.h"
#include "models/foot_rdr.h"
#include "models/foot_ldr.h"

// FRANK CHARACTER
#include "models/waist_uf.h"
#include "models/torso_uf.h"
#include "models/arm_uluf.h"
#include "models/arm_uruf.h"
#include "models/arm_lluf.h"
#include "models/arm_lruf.h"
#include "models/hand_ruf.h"
#include "models/hand_luf.h"
#include "models/leg_uluf.h"
#include "models/leg_uruf.h"
#include "models/leg_lluf.h"
#include "models/leg_lruf.h"
#include "models/foot_ruf.h"
#include "models/foot_luf.h"

// MUMMY CHARACTER
#include "models/waist_um.h"
#include "models/torso_um.h"
#include "models/arm_ulum.h"
#include "models/arm_urum.h"
#include "models/arm_llum.h"
#include "models/arm_lrum.h"
#include "models/hand_rum.h"
#include "models/hand_lum.h"
#include "models/leg_ulum.h"
#include "models/leg_urum.h"
#include "models/leg_llum.h"
#include "models/leg_lrum.h"
#include "models/foot_rum.h"
#include "models/foot_lum.h"

// BRIDE CHARACTER
#include "models/waist_tb.h"
#include "models/torso_tb.h"
#include "models/arm_ultb.h"
#include "models/arm_urtb.h"
#include "models/arm_lltb.h"
#include "models/arm_lrtb.h"
#include "models/hand_rtb.h"
#include "models/hand_ltb.h"
#include "models/leg_ultb.h"
#include "models/leg_urtb.h"
#include "models/leg_lltb.h"
#include "models/leg_lrtb.h"
#include "models/foot_rtb.h"
#include "models/foot_ltb.h"

// WOLFMAN CHARACTER
#include "models/waist_wm.h"
#include "models/torso_wm.h"
#include "models/arm_ulwm.h"
#include "models/arm_urwm.h"
#include "models/arm_llwm.h"
#include "models/arm_lrwm.h"
#include "models/hand_rwm.h"
#include "models/hand_lwm.h"
#include "models/leg_ulwm.h"
#include "models/leg_urwm.h"
#include "models/leg_llwm.h"
#include "models/leg_lrwm.h"
#include "models/foot_rwm.h"
#include "models/foot_lwm.h"

// HORSE CHARACTER
#include "models/waist_ho.h"
#include "models/torso_ho.h"
#include "models/arm_ulho.h"
#include "models/arm_urho.h"
#include "models/arm_llho.h"
#include "models/arm_lrho.h"
#include "models/hand_rho.h"
#include "models/hand_lho.h"
#include "models/leg_ulho.h"
#include "models/leg_urho.h"
#include "models/leg_llho.h"
#include "models/leg_lrho.h"
#include "models/foot_rho.h"
#include "models/foot_lho.h"

// REDUCED BIG PLAYER
#include "models/waist_rm.h"
#include "models/torso_rm.h"
#include "models/arm_ulrm.h"
#include "models/arm_urrm.h"
#include "models/arm_llrm.h"
#include "models/arm_lrrm.h"
#include "models/hand_rrm.h"
#include "models/hand_lrm.h"
#include "models/leg_ulrm.h"
#include "models/leg_urrm.h"
#include "models/leg_llrm.h"
#include "models/leg_lrrm.h"
#include "models/foot_rrm.h"
#include "models/foot_lrm.h"

// UTAH MASCOT
#include "models/waist_ub.h"
#include "models/torso_ub.h"
#include "models/arm_ulub.h"
#include "models/arm_urub.h"
#include "models/arm_llub.h"
#include "models/arm_lrub.h"
#include "models/hand_rub.h"
#include "models/hand_lub.h"
#include "models/leg_ulub.h"
#include "models/leg_urub.h"
#include "models/leg_llub.h"
#include "models/leg_lrub.h"
#include "models/foot_rub.h"
#include "models/foot_lub.h"

// REF CHARACTER
#include "models/waist_rf.h"
#include "models/torso_rf.h"
#include "models/arm_ulrf.h"
#include "models/arm_urrf.h"
#include "models/arm_llrf.h"
#include "models/arm_lrrf.h"
#include "models/hand_rrf.h"
#include "models/hand_lrf.h"
#include "models/leg_ulrf.h"
#include "models/leg_urrf.h"
#include "models/leg_llrf.h"
#include "models/leg_lrrf.h"
#include "models/foot_rrf.h"
#include "models/foot_lrf.h"

// CHEERLEADER CHARACTER
#include "models/waist_cl.h"
#include "models/torso_cl.h"
#include "models/arm_ulcl.h"
#include "models/arm_urcl.h"
#include "models/arm_llcl.h"
#include "models/arm_lrcl.h"
#include "models/hand_rcl.h"
#include "models/hand_lcl.h"
#include "models/leg_ulcl.h"
#include "models/leg_urcl.h"
#include "models/leg_llcl.h"
#include "models/leg_lrcl.h"
#include "models/foot_rcl.h"
#include "models/foot_lcl.h"

// CREATURE CHARACTER
#include "models/waist_uc.h"
#include "models/torso_uc.h"
#include "models/arm_uluc.h"
#include "models/arm_uruc.h"
#include "models/arm_lluc.h"
#include "models/arm_lruc.h"
#include "models/hand_ruc.h"
#include "models/hand_luc.h"
#include "models/leg_uluc.h"
#include "models/leg_uruc.h"
#include "models/leg_lluc.h"
#include "models/leg_lruc.h"
#include "models/foot_ruc.h"
#include "models/foot_luc.h"

// REFLECTION MODELS
#include "models/rft_lch.h"
#include "models/rft_rch.h"
#include "models/rlg_llch.h"
#include "models/rlg_lrch.h"
#include "models/rft_lcb.h"
#include "models/rft_rcb.h"
#include "models/rlg_llcb.h"
#include "models/rlg_lrcb.h"
#include "models/rft_lb.h"
#include "models/rft_rb.h"
#include "models/rlg_llb.h"
#include "models/rlg_lrb.h"
#include "models/rft_lc.h"
#include "models/rft_rc.h"
#include "models/rlg_llc.h"
#include "models/rlg_lrc.h"
#include "models/rft_ltr.h"
#include "models/rft_rtr.h"
#include "models/rlg_lltr.h"
#include "models/rlg_lrtr.h"
#include "models/rft_lhb.h"
#include "models/rft_rhb.h"
#include "models/rlg_llhb.h"
#include "models/rlg_lrhb.h"
#include "models/rft_lah.h"
#include "models/rft_rah.h"
#include "models/rlg_llah.h"
#include "models/rlg_lrah.h"
#include "models/rft_lpg.h"
#include "models/rft_rpg.h"
#include "models/rlg_llpg.h"
#include "models/rlg_lrpg.h"
#include "models/rft_ls.h"
#include "models/rft_rs.h"
#include "models/rlg_lls.h"
#include "models/rlg_lrs.h"
#include "models/rft_ldr.h"
#include "models/rft_rdr.h"
#include "models/rlg_lldr.h"
#include "models/rlg_lrdr.h"
#include "models/rft_lss.h"
#include "models/rft_rss.h"
#include "models/rlg_llss.h"
#include "models/rlg_lrss.h"
#include "models/rft_lub.h"
#include "models/rft_rub.h"
#include "models/rlg_llub.h"
#include "models/rlg_lrub.h"
#include "models/rft_la.h"
#include "models/rft_ra.h"
#include "models/rlg_lla.h"
#include "models/rlg_lra.h"
#include "models/rft_lj.h"
#include "models/rft_rj.h"
#include "models/rlg_llj.h"
#include "models/rlg_lrj.h"
#include "models/rft_ln.h"
#include "models/rft_rn.h"
#include "models/rlg_lln.h"
#include "models/rlg_lrn.h"
#include "models/rft_lf.h"
#include "models/rft_rf.h"
#include "models/rlg_llf.h"
#include "models/rlg_lrf.h"
#include "models/rft_lom.h"
#include "models/rft_rom.h"
#include "models/rlg_llom.h"
#include "models/rlg_lrom.h"
#include "models/rft_lcc.h"
#include "models/rft_rcc.h"
#include "models/rlg_llcc.h"
#include "models/rlg_lrcc.h"
#include "models/rft_lp.h"
#include "models/rft_rp.h"
#include "models/rlg_llp.h"
#include "models/rlg_lrp.h"
#include "models/rft_lho.h"
#include "models/rft_rho.h"
#include "models/rlg_llho.h"
#include "models/rlg_lrho.h"
#include "models/rft_lw.h"
#include "models/rft_rw.h"
#include "models/rlg_llw.h"
#include "models/rlg_lrw.h"
#include "models/rft_luf.h"
#include "models/rft_ruf.h"
#include "models/rlg_lluf.h"
#include "models/rlg_lruf.h"
#include "models/rft_lum.h"
#include "models/rft_rum.h"
#include "models/rlg_llum.h"
#include "models/rlg_lrum.h"
#include "models/rft_ltb.h"
#include "models/rft_rtb.h"
#include "models/rlg_lltb.h"
#include "models/rlg_lrtb.h"
#include "models/rft_lwm.h"
#include "models/rft_rwm.h"
#include "models/rlg_llwm.h"
#include "models/rlg_lrwm.h"
#include "models/rft_lrm.h"
#include "models/rft_rrm.h"
#include "models/rlg_llrm.h"
#include "models/rlg_lrrm.h"
#include "models/rft_luc.h"
#include "models/rft_ruc.h"
#include "models/rlg_lluc.h"
#include "models/rlg_lruc.h"

#include "models/skeleton.h"
