all:
	@echo Making DUMPBOD
	@$(MAKE) --no-print-directory -C dumpbod

clobber:
	@echo Clobbering dumpbod
	@$(MAKE) --no-print-directory -C dumpbod clobber

clean:
	@echo Cleaning dumpbod
	@$(MAKE) --no-print-directory -C dumpbod clean

rebuild:
	@echo Rebuilding dumpbod
	@$(MAKE) --no-print-directory -C dumpbod rebuild
